name: "📢 Feedback"
description: Provide feedback about specific sections of the implementation guide.
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        <!-- The following fields are stored as hidden comments for easier searching -->

  - type: input
    id: filename
    attributes:
      label: Hidden: filename
      description: Hidden field for filename.
      placeholder: "e.g., index.html"
      value: ""
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Hidden: page
      description: Hidden field for page URL.
      placeholder: "e.g., https://example.org/page.html"
      value: ""
    validations:
      required: true

  - type: input
    id: section
    attributes:
      label: Hidden: section
      description: Hidden field for section.
      placeholder: "e.g., home page"
      value: ""
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: "Describe your feedback clearly."
      placeholder: "Write your feedback here..."
    validations:
      required: true
