name: "📢 Feedback"
description: Provide feedback about specific sections of the implementation guide.
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: input
    id: filename
    attributes:
      label: Filename
      description: "Name of the file (e.g., index.html)"
      placeholder: "index.html"
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Page URL
      description: "Link to the page you're giving feedback on"
      placeholder: "https://your-ig.org/page.html#section"
    validations:
      required: true

  - type: input
    id: section
    attributes:
      label: Section
      description: "Name of the section your feedback relates to"
      placeholder: "e.g., home"
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Feedback Description
      description: "Describe the issue, suggestion, or improvement clearly."
      placeholder: "This section needs clarification..."
      value: |
        <!-- filename: {{ filename }} -->
        <!-- page: {{ page }} -->
        <!-- section: {{ section }} -->

    validations:
      required: true
